### ISSUE TITLE
Require silverstripe-maintenance module

### ISSUE THREAD

**Issue by raissanorth** [spekulatius/silverstripe-composer-versions#8]
Make https://github.com/bringyourownideas/silverstripe-maintenance a module requirement.

**Comment by spekulatius** [comment]
Hello @raissanorth 

thanks for opening the issues. I originally left it open for anyone to decide if they are interested in using the maintenance module. As it seems no one used this. I'll add the requirement over the three repos.

Cheers,
Peter

**Comment by spekulatius** [comment]
I've added the maintenance module as a dependency over the three repos @raissanorth.

**Comment by raissanorth** [comment]
Fabulous, thanks Peter!
